config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    resources :sizes
  end
end

app/models/spree/backend_configuration_decorator.rb
Spree::BackendConfiguration.class_eval do
  SIZE_TABS ||= [:sizes]
end

app/models/spree/size.rb
module Spree
  class Size < Spree::Base
    validates :name, presence: true
  end
end

app/controllers/spree/admin/sizes_controller.rb
module Spree
  module Admin
    class SizesController < ResourceController
      include Spree::Admin::BaseHelper
      rescue_from ActiveRecord::RecordNotFound, with: :render_404

      before_action :load_size, only: [:edit, :destroy]

      def index
        respond_with(@collection)
      end

      def create
        @size = Spree::Size.new(size_params)
        if @size.save
          flash.now[:success] = flash_message_for(@size, :successfully_created)
          render :edit
        else
          render :new
        end
      end

      def destroy
        if @size.destroy
          flash[:success] = Spree.t('notice_messages.size_deleted')
        else
          flash[:error] = Spree.t('notice_messages.size_not_deleted')
        end

        respond_with(@size) do |format|
          format.html { redirect_to admin_ranges_path }
          format.js  { render_js_for_destroy }
        end
      end

      private

      def size_params
        params.fetch(:size, {}).permit(*permitted_attributes)
      end

      def permitted_attributes
        [
          :name,
          :description
        ]
      end

      def load_size
        @size = Spree::Size.find(params[:id])
      end

      def collection
        return @collection if @collection.present?
        # params[:q] can be blank upon pagination
        params[:q] ||= {}

        @search = Spree::Size.ransack(params[:q])
        @collection = @search.result.
              page(params[:page]).
              per(Spree::Config[:properties_per_page])
      end

    end
  end
end

app/views/spree/admin/sizes/_form.html.erb
<div class='row' data-hook='admin_size_form_fields'>
  <div class='col-md-6' data-hook='admin_size_form_name'>
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, raw(Spree.t(:name) + content_tag(:span, ' *', class: 'required')) %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>

  <div class='col-md-6' data-hook='admin_size_form_descriptoion'>
    <%= f.field_container :description, class: ['form-group'] do %>
      <%= f.label :description, raw(Spree.t(:description)) %>
      <%= f.text_field :description, class: 'form-control' %>
      <%= f.error_message_on :description %>
    <% end %>
  </div>
</div>

app/views/spree/admin/sizes/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:sizes), admin_sizes_path %> /
  <%= @size.name %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @size } %>

<%= form_for [:admin, @size], method: :put, html: { multipart: true } do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/sizes/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:sizes) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_size), new_object_url, { class: 'btn-success', icon: 'add', id: 'admin_new_size' } %>
<% end if can?(:create, Spree::Size) %>

<% content_for :table_filter do %>
  <div data-hook='admin_size_sidebar'>

    <%= search_form_for [:admin, @search] do |f| %>
      <% locals = { f: f } %>
      <div data-hook='admin_size_index_search' class='row'>
        <div class='col-md-6'>
          <div class='form-group'>
            <%= f.label :name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, size: 15, class: 'form-control js-quick-search-target' %>
          </div>
        </div>
      </div>
      <div data-hook='admin_size_index_search_buttons' class='form-actions'>
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>

  </div>
<% end %>

<% if @collection.any? %>
  <table class='table' id='listing_sizes'>
    <thead>
      <tr data-hook='admin_size_index_headers'>
        <th>
          <%= sort_link @search, :name, Spree.t(:name), { default_order: 'desc' }, { title: 'admin_size_listing_name_title' } %>
        </th>
        <th>
          <%= Spree.t(:description) %>
        </th>
        <th>
          <%= Spree.t(:category) %>
        </th>
        <th class='actions' data-hook='admin_size_index_header_actions'></th>
      </tr>
    </thead>

    <tbody>
      <% @collection.each do |size| %>
        <tr id='<%= spree_dom_id size %>' data-hook='admin_size_index_rows' class='<%= cycle('odd', 'even') %>'>
          <td class='name'><%= size.name %></td>
          <td class='description'><%= size.description %></td>
          <td class='category'><%= size.category %></td>
          <td class='actions actions-2 text-right' data-hook='admin_size_index_row_actions'>
            <%= link_to_edit size, no_text: true, class: 'edit' if can?(:edit, size) %>
            <%= link_to_delete size, no_text: true if can?(:delete, size) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class='alert alert-info no-objects-found'>
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Size)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

app/views/spree/admin/sizes/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @size } %>

<% content_for :page_title do %>
  <%= Spree.t(:new_size) %>
<% end %>

<%= form_for [:admin, @size], html: { multipart: true } do |f| %>
  <fieldset data-hook='new_range'>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>